In [2]:
import numpy as np
import time

## Vector Creation

In [3]:
# Numpy routines which alloctae memory and fill arrays with values.
a = np.zeros(4);     print(f"np.zeros(4):  a = {a}, a shape ={a.shape}, a data type = {a.dtype}")
a = np.zeros((4,));  print(f"np.zeros(4,) : a={a}, a shape ={a.shape}, a data type = {a.dtype}")
a = np.random.random_sample(4); print(f"np.random.random_sample(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.zeros(4):  a = [0. 0. 0. 0.], a shape =(4,), a data type = float64
np.zeros(4,) : a=[0. 0. 0. 0.], a shape =(4,), a data type = float64
np.random.random_sample(4): a = [0.03827962 0.60083278 0.71655446 0.03779291], a shape = (4,), a data type = float64


In [6]:
# NumPy routines which allocate memory and fill arrays with value but do not accept shape as input argument
a = np.arange(4.);              print(f"np.arange(4.):     a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.rand(4);          print(f"np.random.rand(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.arange(4.):     a = [0. 1. 2. 3.], a shape = (4,), a data type = float64
np.random.rand(4): a = [0.42617388 0.25793919 0.26840283 0.76818449], a shape = (4,), a data type = float64


In [8]:
a= np.array([5,4,3,2])
a

array([5, 4, 3, 2])

In [9]:
b =   np.array([5.,4,3,2])
b

array([5., 4., 3., 2.])

## Operations On Vectors

In [13]:
#vector indexing operation on 1-D vectors
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
#access an element
print(f"a[2].shape: {a[2].shape}  a[2] = {a[2]}")

a[2].shape: ()  a[2] = 2


In [20]:
# access the last element, negative indexes count from the end
#print(f"a[-1]={a[-1]}")
a[-1]

9

In [24]:
# indexes muts be within the range of the vector or they wil produce and error
try:
    c=a[10]
except Exception as e:
    print(e)

index 10 is out of bounds for axis 0 with size 10


## Slicing

In [26]:
#Vector slicing operation
a  = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
#access 5 consecutive elements (start:stop:step)
c = a[2:7:1]
c

array([2, 3, 4, 5, 6])

In [29]:
c = a[2:7:2]
c

array([2, 4, 6])

In [30]:
c = a[3:]
c

array([3, 4, 5, 6, 7, 8, 9])

In [31]:
c = a[:3]
c

array([0, 1, 2])

In [32]:
c = a[:]
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Single Vector Operationx

In [34]:
a = np.array([1,2,3,4])
print(f"a:{a}")

a:[1 2 3 4]


In [36]:
b = -a
print(f"b=-a:{b}")

b=-a:[-1 -2 -3 -4]


In [37]:
b = np.sum(a)
print(f"b = np.sum(a): {b}")

b = np.sum(a): 10


In [38]:
b = np.mean(a)
print(f"b = np.mean(a): {b}")

b = np.mean(a): 2.5


In [39]:
b =  a**2
print(f"b = a**2: {b}")

b = a**2: [ 1  4  9 16]


## 3.4.4 Vector Vector element-wise operations

In [41]:
a = np.array([1,2,3,4])
b = np.array([-1,-2,-3,-4])
print(f"Binary operators work element wise: {a + b}")

Binary operators work element wise: [0 0 0 0]


In [43]:
# try a mismatched vector operation
c = np.array([1,2])
try:
    d = a + c
except Exception as e :
    print("The error message you'll see is:")
    print(e)

The error message you'll see is:
operands could not be broadcast together with shapes (4,) (2,) 


## 3.4.5 Vector Operations

In [48]:
a =  np.array([1, 2, 3,4])

# multiply a by a scalar
b = 5 * a
b


array([ 5, 10, 15, 20])

# 3.4.6 Vector Vector dot Product

In [50]:
def my_dot(a, b):
    """ 
    Compute the dot product of two vectors

    Args:
        a (ndarray (n,)): input vector
        b (ndarray (n,)): input vector with same dimension as a

    Returns:
    x (scalar):
    """
    x = 0
    for i in range (a.shape[0]):
        x = x+ a[i] * b[i]
        return x

In [56]:
# test 1-D
a = np.array([1,2,3,4])
b =  np.array([-1, 4, 3, 2])
print(f"my_dot(a, b) = {my_dot(a, b)}")

my_dot(a, b) = -1


In [55]:
# test 1-D
a = np.array([1,2,3,4])
b = np.array([-1, 4, 3, 2])
c = np.dot(a, b)
c

24

# 3.4.7 The Need for Speed: Vector Vs for loop

In [63]:
np.random.seed(1)
a = np.random.rand(10000000)    # very large arrays
b = np.random.rand(10000000)

tic = time.time()  # capture start time
c =  np.dot(a, b)
toc = time.time()  # capture end time
print(f"{c: .2f}")

 2501072.58


In [67]:
print(f"{1000*(toc-tic):.4f}ms")

9.9738ms


In [68]:
toc

1713543552.847993

In [69]:
tic

1713543552.8380191

dtype('float64')

## 3.4.8 Vector Vector Operations 

In [79]:
# show common 
X = np.array([[1],[2],[3],[4]])
w = np.array([2])
c = np.dot(X[1], w)

X[1].shape, w.shape, c.shape

((1,), (1,), ())

## Matrices

In [82]:
a = np.zeros((1, 5))
print(f"a  shape = {a.shape}, a={a}")

a = np.zeros((2,  1))
print(f"a shape = {a.shape}, a = {a}")

a = np.random.random_sample((1, 1))
print(f"a shape = {a.shape}, a ={a}")

a  shape = (1, 5), a=[[0. 0. 0. 0. 0.]]
a shape = (2, 1), a = [[0.]
 [0.]]
a shape = (1, 1), a =[[0.44236513]]


In [83]:
# Numpy routines which allocate memory and fill with user specified values

a = np.array([[5], [4], [3]]);  print(f" a shape = {a.shape}, np.array: a = {a}")
a = np.array([[5],
              [4],
              [3]])
print(f" a shape =  {a.shape}, np.array: a={a}")

 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]
 a shape =  (3, 1), np.array: a=[[5]
 [4]
 [3]]


# 4.4 Operations On Matrices

In [97]:
a = np.arange(30).reshape(-1, 10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [95]:
a[0, 2:7:1]

array([2, 3, 4, 5, 6])

In [98]:
a[:, 2:7:1]

array([[ 2,  3,  4,  5,  6],
       [12, 13, 14, 15, 16],
       [22, 23, 24, 25, 26]])

In [99]:
a[:,:] 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [101]:
a[1,:]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [102]:
a[0, :]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])